<?php
    $title = "Marmita da Dona Rita";
    $desenvolvedor = "Cleo";

    $marmitas = array(
        0 => array('id'=>'1', 
            'titulo'=>'Delicias Japonesas',  
            'data'=>'2022-08-13', 
            'descricao'=>'Sushi, Sachimi, Salmão, Atum, Pepino, Arroz',
            'imagem'=>'img/img1.jpg', 
            'title_img'=>'Delicias Japonesas'),
        1 => array('id'=>'2', 
            'titulo'=>'Filé de Frango com Salada',  
            'data'=>'2022-08-13', 
            'descricao'=>'Filé de Frango, Ervilha, Cenoura, Vagem',
            'imagem'=>'img/img2.jpg', 
            'title_img'=>'Filé de Frango com Salada'),
        2 => array('id'=>'3', 
            'titulo'=>'Penne com Tomate Seco', 
            'data'=>'2022-08-13', 
            'descricao'=>'Penne com Tomate Seco',
            'imagem'=>'img/img3.jpg', 
            'title_img'=>'Marmita Caseira nº 3'),
        3 => array('id'=>'4', 
            'titulo'=>'Paella Espanhola', 
            'data'=>'2022-08-13', 
            'descricao'=>'Arroz, Pimentão, Açafrão, Camarão, Mariscos, Peixe',
            'imagem'=>'img/img4.jpg', 
            'title_img'=>'Paella Espanhola'),
        4 => array('id'=>'5', 
            'titulo'=>'Salmão com Salada', 
            'data'=>'2022-08-13', 
            'descricao'=>'Salmão, Vagem, Cenoura, Tomate, Ervilha',
            'imagem'=>'img/img5.jpg', 
            'title_img'=>'Salmão com Salada'),
        5 => array('id'=>'6', 
            'titulo'=>'Frango Xadrez com Couve Flor', 
            'data'=>'2022-08-13', 
            'descricao'=>'Frango, Pimentão, Cebola, TomateCouve Flor',
            'imagem'=>'img/img6.jpg', 
            'title_img'=>'Frango Xadrês'),
        6 => array('id'=>'7', 
            'titulo'=>'Lombinho com Tomate Assado e Salada', 
            'data'=>'2022-08-13', 
            'descricao'=>'Lombinho, Tomate Assado, Cenoura, Pepino',
            'imagem'=>'img/img7.jpg', 
            'title_img'=>'Lombinho com Tomate Assado e Salada'),
        7 => array('id'=>'8', 
            'titulo'=>'Picadinho de Carne com Fritas', 
            'data'=>'2022-08-13', 
            'descricao'=>'Picadinho de Carne, Arroz e Fritas',
            'imagem'=>'img/img8.jpg', 
            'title_img'=>'Picadinho de Carne com Fritas'),
    );